name: 'CI'

on:
  push:
    branches:
    - master
    - development
    - features/**
    tags:
    - '*.*.*'
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - run: dotnet --info
  
    - name: Build
      run: |
        chmod +x "./build.cmd"
        chmod +x "./build.ps1"
        chmod +x "./build.sh"

    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/tags/')
      run: ./build.ps1
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/master' && contains(github.ref, 'refs/tags/'))
      run: ./build.ps1
